### ISSUE TITLE
Maybe add some process logs, I do not know it is stuck or not

### ISSUE THREAD

**Issue by Vanyoo** [jumpycalm/pn532-cloner#11]
Thanks, author, it is a good project.
When it showed me ETA is 25 minutes, using 16 threads, I am so happy.
But almost 40 minutes passed, it still does not print anything, make me confused.And it seems only use 2 threads?

![image](https://github.com/jumpycalm/pn532-cloner/assets/10300206/394d647f-f0e8-409f-adfd-476970ce01f8)
![image](https://github.com/jumpycalm/pn532-cloner/assets/10300206/cccb378b-0784-4764-871d-4fc4972829a8)
![image](https://github.com/jumpycalm/pn532-cloner/assets/10300206/33b10cfb-0c09-4f38-9cfc-d7eb7ff9ac1a)

**Comment by jumpycalm** [comment]
The issue was caused by reading a tag that is a static nonce tag. This type of tag is not seen in the USA. It won't get supported in the near future. I'm closing it as a duplicate of the issue "Add support for static nonce MFC tags"
