### ISSUE TITLE
Add support to "Fully Encrypted Mirare" 

### ISSUE THREAD

**Issue by filiboni** [jumpycalm/pn532-cloner#9]
Hi, unfortunately when I try to read my tag with the Pn532 the program says "fully encrypted mifare Classic" not supported, could you add support for these cards!
Many thanks!

**Comment by jumpycalm** [comment]
Please provide the following information:
1. Picture of the tag.
2. Picture of the reader/lock the tag is used at.
3. Country/region where the tag is used.

**Comment by jumpycalm** [comment]
No response from the reporter, closing the issue.
